//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Final_5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DateTimeByDoctor
    {
        public int Id { get; set; }
        public string idDoctor { get; set; }
        public string practicsName { get; set; }
        public System.DateTime insertDate { get; set; }
        public string turnId { get; set; }
    
        public virtual Doctor Doctor { get; set; }
    }
}
