//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Final_5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MedicalSheet
    {
        public int Id { get; set; }
        public int turnId { get; set; }
        public string userId { get; set; }
        public Nullable<System.DateTime> dateTime { get; set; }
        public string comment { get; set; }
        public string medicineName { get; set; }
    
        public virtual Medicine Medicine { get; set; }
        public virtual Turn Turn { get; set; }
    }
}
