//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Final_5.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Database1Entities : DbContext
    {
        public Database1Entities()
            : base("name=Database1Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Brunch> Brunch { get; set; }
        public virtual DbSet<Doctor> Doctor { get; set; }
        public virtual DbSet<Practics> Practics { get; set; }
        public virtual DbSet<Turn> Turn { get; set; }
        public virtual DbSet<Medicine> Medicine { get; set; }
        public virtual DbSet<MedicalSheet> MedicalSheet { get; set; }
        public virtual DbSet<DateTimeByDoctor> DateTimeByDoctor { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<SendData> SendData { get; set; }
    }
}
