//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Final_5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SendData
    {
        public int Id { get; set; }
        public string userId { get; set; }
        public string idDoctor { get; set; }
        public string sendData1 { get; set; }
        public Nullable<bool> isSign { get; set; }
        public System.DateTime dateInsert { get; set; }
        public string toUserId { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
