//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Final_5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Turn
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Turn()
        {
            this.MedicalSheet = new HashSet<MedicalSheet>();
        }
    
        public int Id { get; set; }
        public string userId { get; set; }
        public string practicsName { get; set; }
        public string date { get; set; }
        public string hour { get; set; }
        public string city { get; set; }
        public string comment { get; set; }
        public string medicineName { get; set; }
    
        public virtual Practics Practics { get; set; }
        public virtual Medicine Medicine { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MedicalSheet> MedicalSheet { get; set; }
    }
}
